apiVersion: v1
kind: Service
metadata:
  name: kubevault-operator
  namespace: ${KUBEVAULT_NAMESPACE}
  labels:
    app: vault-operator
spec:
  ports:
  - name: api
    port: 443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
---
# To get to the host machine from the VM,
# the IP is 10.0.2.2 (by convention)
# ref: https://stackoverflow.com/questions/9537751/virtualbox-port-forward-from-guest-to-host
apiVersion: v1
kind: Endpoints
metadata:
  name: kubevault-operator
  namespace: ${KUBEVAULT_NAMESPACE}
  labels:
    app: vault-operator
subsets:
- addresses:
  - ip: 10.0.2.2
  ports:
  - name: api
    port: 8443
    protocol: TCP
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.admission.kubevault.com
  labels:
    app: vault-operator
spec:
  insecureSkipTLSVerify: true
  group: admission.kubevault.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: kubevault-operator
    namespace: ${KUBEVAULT_NAMESPACE}
  version: v1alpha1
---
# register as aggregated apiserver
# apiVersion: apiregistration.k8s.io/v1beta1
# kind: APIService
# metadata:
#   name: v1alpha1.mutators.kubedb.com
#   labels:
#     app: kubedb
# spec:
#   insecureSkipTLSVerify: true
#   group: mutators.kubedb.com
#   groupPriorityMinimum: 1000
#   versionPriority: 15
#   service:
#     name: kubedb-operator
#     namespace: ${KUBEVAULT_NAMESPACE}
#   version: v1alpha1
