apiVersion: v1
kind: Namespace
metadata:
  name: vault
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:0.8.3
          args:
            - "server"
            - "-dev"
            - "-log-level=debug"
            - "-dev-root-token-id=goldfish"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
  namespace: vault
spec:
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: vault
