---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: vault
  name: awsroles.engine.kubevault.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    type: string
  group: engine.kubevault.com
  names:
    categories:
    - vault
    - appscode
    - all
    kind: AWSRole
    plural: awsroles
    singular: awsrole
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
